name: Weekly Vacancy Search

on:
  schedule:
    - cron: '0 11 * * 1'
  workflow_dispatch:

jobs:
  search:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 gspread google-auth selenium webdriver-manager gigachat

      - name: Debug files
        run: |
          echo "Current directory:"
          pwd
          echo "Files:"
          ls -la
          echo "Python files:"
          find . -type f -name "*.py"

      - name: Run script
        env:
          GIGACHAT_KEY: ${{ secrets.GIGACHAT_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          python ./main.py
